openapi: "3.0.0"
info:
  title: "FabFusion REST Backend API"
  description: "API documentation for the e-commerce website - FabFusion"
  version: "1.0.0"

servers:
  - url: "http://localhost:8000/api"
    description: "Local server"

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: "612f23c8f7284a0015e05b72"
        email:
          type: string
          example: "example@gmail.com"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00.000Z"

