openapi: 3.0.0
info:
  title: Image Upload API
  description: API for uploading and deleting images using Cloudinary.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/upload
paths:
  /:
    post:
      summary: Upload images
      operationId: uploadImages
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - images
      responses:
        '200':
          description: Images uploaded successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Bad request

  /delete-img/{id}:
    delete:
      summary: Delete an image
      operationId: deleteImages
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Image deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Deleted
        '404':
          description: Image not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
